### ISSUE TITLE
max_iter should be max_iters

### ISSUE THREAD

**Issue by mmor92** [dschmitz89/Polyfit#6]
In line 329 of the main function, it should be max_iters instead of max_iter

https://github.com/dschmitz89/Polyfit/blob/0a269b27b6b4f5873964a16e3c78d3440e9a945a/polyfit/polyfit.py#L328

**Comment by dschmitz89** [comment]
Hi there,

according to cvxpy docs `max_iter` is correct: https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options
For OSQP it is called `max_iter`, for ECOS `max_iters` .
