### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by HansLeonardVanBrueggemann** [dschmitz89/Polyfit#7]
Hi there! 

finally found the package I was looking for but I can't seem to install it 

Mac OS - M2 chip - I get the following error 

`
error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/*BLINDED*/opt/miniconda3/envs/inter/include -arch arm64 -fPIC -O2 -isystem /Users/*BLINDED*/opt/miniconda3/envs/inter/include -arch arm64 -c /var/folders/5h/skwjvwqs1v1fx5m4gqkcfq680000gn/T/tmpqjocj0sd/source.c -o /var/folders/5h/skwjvwqs1v1fx5m4gqkcfq680000gn/T/tmpqjocj0sd/var/folders/5h/skwjvwqs1v1fx5m4gqkcfq680000gn/T/tmpqjocj0sd/source.o -MMD -MF /var/folders/5h/skwjvwqs1v1fx5m4gqkcfq680000gn/T/tmpqjocj0sd/var/folders/5h/skwjvwqs1v1fx5m4gqkcfq680000gn/T/tmpqjocj0sd/source.o.d" failed with exit status 1
`

**Comment by dschmitz89** [comment]
Hi there,

this looks like an issue with `cvxpy` as `polyfit` does not need to compile anything. For installing `cvxpy` on Mac, please check their installation [guidelines](https://www.cvxpy.org/install/). In general, many packages using low-level stuff are unfortunately still problematic to install on Mac/ARM.
